Ces 42 Store occurrence instance
hhtank/liferay-portal pull request #19
Opened 2019-06-17 10:25 UTC by VuHoDac

https://issues.liferay.com/browse/CES-42

2019-06-17 11:27 UTC, hhtank requested changes
Let's consider some changes for this implementation

2019-06-17 11:27 UTC, hhtank commented on modules/apps/powwow/powwow-portlet/docroot/WEB-INF/service.xml
> +
for now, i found that we better should have fields for `startTime` and `endTime`, which could be easier for us to handle logic relate to occurrences. Let's add 2 those fields. Please ensure that the time is using the correct time zone, could probably get from `calendarBooking`. In `zoomOriginalData`, i think time zone is default UTC, we may need to convert when storing into occurrence object.

2019-06-17 11:27 UTC, hhtank commented on modules/apps/powwow/powwow-portlet/docroot/WEB-INF/src/com/liferay/powwow/meetings/portlet/MeetingsPortlet.java
> +			PowwowMeeting powwowMeetingUpdated = null;
is it necessary to have a separate variable `powwowMeetingUpdated`?

2019-06-17 11:27 UTC, hhtank commented on modules/apps/powwow/powwow-portlet/docroot/WEB-INF/src/com/liferay/powwow/meetings/portlet/MeetingsPortlet.java
> +			powwowMeetingOccurrence.setOccurrenceStatus(occurrenceJSONObject.getString("status"));
we should define our own enum to represent occurrence status

2019-06-17 11:27 UTC, hhtank commented on modules/apps/powwow/powwow-portlet/docroot/WEB-INF/src/com/liferay/powwow/provider/PowwowServiceProvider.java
> +	public JSONObject getZoomMeetingJSONObject(long powwowMeetingId);
Let's consider the name `getMeetingJSONObject`

2019-06-17 11:27 UTC, hhtank commented on modules/apps/powwow/powwow-portlet/docroot/WEB-INF/src/com/liferay/powwow/meetings/portlet/MeetingsPortlet.java
> +		PowwowMeeting powwowMeeting =
should we collect this logic into a method `PowwowMeetingOccurrenceLocalServiceUtil.deleteByPowwowMeetingId`. In the method, find all occurrence and remove it there?

2019-06-17 11:27 UTC, hhtank commented on modules/apps/powwow/powwow-portlet/docroot/WEB-INF/src/com/liferay/powwow/meetings/portlet/MeetingsPortlet.java
> +
let's have a service method `addPowwowMeetingOccurrence(params...)` which accepts instance's params and some of audit fields if possible

2019-06-17 11:27 UTC, hhtank commented on modules/apps/powwow/powwow-portlet/docroot/WEB-INF/src/com/liferay/powwow/service/impl/PowwowMeetingOccurrenceLocalServiceImpl.java
> + * @author Shinn Lok
update the author name

2019-06-18 08:32 UTC, VuHoDac commented
updated

2019-06-19 02:24 UTC, hhtank reviewed
i made refactor, please see in my commit for things could be improved.
beside that, we should add permission checking later on.

2019-06-19 02:24 UTC, hhtank commented on modules/apps/powwow/powwow-portlet/docroot/WEB-INF/src/com/liferay/powwow/meetings/portlet/MeetingsPortlet.java
> +	private static final DateFormat occurrenceTimeFormat = DateFormatFactoryUtil.getSimpleDateFormat(
DateFormat is not thread safe, it should not be used as `static`

2019-06-19 02:24 UTC, hhtank commented on modules/apps/powwow/powwow-portlet/docroot/WEB-INF/src/com/liferay/powwow/meetings/portlet/MeetingsPortlet.java
> +		"yyy-MM-dd'T'HH:mm:ss'Z'", TimeZone.getTimeZone(StringPool.UTC));
typo `yyy`

2019-06-19 02:24 UTC, hhtank commented on modules/apps/powwow/powwow-portlet/docroot/WEB-INF/src/com/liferay/powwow/service/impl/PowwowMeetingOccurrenceLocalServiceImpl.java
> +	/*
remove this comment

2019-06-19 02:24 UTC, hhtank commented on modules/apps/powwow/powwow-portlet/docroot/WEB-INF/src/com/liferay/powwow/service/impl/PowwowMeetingOccurrenceLocalServiceImpl.java
> +		long powwowMeetingId, String occurrenceId, String occurrenceStatus, String zoomOriginalData, long startTime,
add audit data

2019-06-19 02:24 UTC, hhtank commented on modules/apps/powwow/powwow-portlet/docroot/WEB-INF/src/com/liferay/powwow/meetings/portlet/MeetingsPortlet.java
> +			if (calendarBooking.isRecurring()) {
consider as a TODO: do we need to check if recurring was updated or not?

2019-06-19 02:24 UTC, hhtank commented on modules/apps/powwow/powwow-portlet/docroot/WEB-INF/src/com/liferay/powwow/meetings/portlet/MeetingsPortlet.java
> +		Calendar startTimeCalendar = CalendarFactoryUtil.getCalendar(timeZone);
double check correctness of time zone.

2019-06-19 02:24 UTC, hhtank commented on modules/apps/powwow/powwow-portlet/docroot/WEB-INF/src/com/liferay/powwow/service/impl/PowwowMeetingOccurrenceLocalServiceImpl.java
> +	@Indexable(type = IndexableType.DELETE)
remove this annotation

2019-06-19 02:24 UTC, hhtank commented on modules/apps/powwow/powwow-portlet/docroot/WEB-INF/src/com/liferay/powwow/service/impl/PowwowMeetingOccurrenceLocalServiceImpl.java
> +			powwowMeetingOccurrencePersistence.remove(meetingOccurrence);
call `powwowMeetingOccurrenceLocalService` to trigger indexer

2019-06-19 02:24 UTC, hhtank commented on modules/apps/powwow/powwow-portlet/docroot/WEB-INF/src/com/liferay/powwow/service/impl/PowwowMeetingOccurrenceLocalServiceImpl.java
> +		long powwowMeetingId, String occurrenceId, String occurrenceStatus, String zoomOriginalData, long startTime,
use enum for `occurrenceStatus`

2019-06-19 02:24 UTC, hhtank commented on modules/apps/powwow/powwow-portlet/docroot/WEB-INF/src/com/liferay/powwow/meetings/portlet/MeetingsPortlet.java
> +			if (calendarBooking.isRecurring()) {
if previously this was a recurring meeting and now changed to non-recurring, then we need to delete recurring

2019-06-19 02:24 UTC, hhtank commented on modules/apps/powwow/powwow-portlet/docroot/WEB-INF/src/com/liferay/powwow/meetings/portlet/MeetingsPortlet.java
> +		CalendarBooking calendarBooking = CalendarBookingLocalServiceUtil.fetchCalendarBooking(calendarBookingId);
because this method is called in a loop, we should be able to reuse the instance like `calendarBooking` and similar objects.

2019-06-19 02:25 UTC, closed without merging