LPS-166515 The LAR files used for Site Template propagation to be removed from the Document and Media library
hhtank/liferay-portal pull request #38
Opened 2023-02-10 06:35 UTC by tototrinh

Hi @hhtank,
Please help review this PR and leave your comments. Thanks.
Ticket: https://issues.liferay.com/browse/LPS-166512

2023-02-10 06:35 UTC, liferay-continuous-integration commented
To conserve resources, the PR Tester does not automatically run for every pull.

If your code changes were already tested in another pull, reference that pull in this pull so the test results can be analyzed.

If your pull was never tested, comment &quot;ci:test&quot; to run the PR Tester for this pull.

2023-02-10 06:36 UTC, tototrinh commented
ci:test:sf

2023-02-10 06:36 UTC, liferay-continuous-integration commented
Closing pull request because pulls for reference LPS-166515 should not be sent to repository liferay-portal

2023-02-10 06:36 UTC, tototrinh commented
ci:reopen

2023-02-10 06:37 UTC, tototrinh commented
ci:test

2023-02-10 06:37 UTC, liferay-continuous-integration commented
Closing pull request because pulls for reference LPS-166515 should not be sent to repository liferay-portal

2023-02-10 06:37 UTC, tototrinh commented
ci:reopen

2023-02-13 10:07 UTC, hhtank requested changes
Things to clarify:
- The AC only mentions removal of LAR file that are used for ST propagation, so maybe we need to remove the `fileEntry` (attached to the backgroundTask) instead of deleting the backgroundTask itself?
- Should the removal handling only happens on each import task?

2023-02-13 10:07 UTC, hhtank commented on portal-kernel/src/com/liferay/exportimport/kernel/background/task/BackgroundTaskContextMapConstants.java
> +package com.liferay.exportimport.kernel.background.task;
Is there any good reason that motivated us to move this class?

2023-02-13 10:07 UTC, hhtank commented on modules/apps/export-import/export-import-service/src/main/java/com/liferay/exportimport/internal/background/task/LayoutSetPrototypeImportBackgroundTaskExecutor.java
> +				List<BackgroundTask> deleteBackgroundTasks =
There are things we may need a session to discuss the details for this feature. Just in case, if we would need to query background tasks here, should we use `getBackgroundTasks(long groupId, String taskExecutorClassName, int status)` to only filter by status like SUCCESS and could be also FAIL/CANCELLED? Which could reduce the number of records returned.

2023-02-14 08:54 UTC, tototrinh commented
Hi @hhtank, I have updated the code based on the our discussion, please help take a look again. Thanks.

2023-02-16 06:43 UTC, merged

2023-02-16 06:44 UTC, hhtank commented
Looks good to me, thanks!