LPS-179688 As an Instance Administrator, I want to be able to configure that if the users have the option to give their password at registration
hhtank/liferay-portal pull request #44
Opened 2023-05-09 06:29 UTC by thabet91

2023-05-10 00:49 UTC, hhtank requested changes

2023-05-10 00:49 UTC, hhtank commented on modules/apps/account/account-admin-web/src/main/resources/META-INF/resources/account_user_registration/create_account_user.jsp
>  			<div class="form-group">
should we hide the `div` form-group as well?

2023-05-10 00:49 UTC, hhtank commented on modules/apps/account/account-admin-web/src/main/resources/META-INF/resources/account_user_registration/create_account_user.jsp
> +			<c:if test="<%= PrefsPropsUtil.getBoolean(company.getCompanyId(), PropsKeys.LOGIN_CREATE_ACCOUNT_ALLOW_CUSTOM_PASSWORD, PropsValues.LOGIN_CREATE_ACCOUNT_ALLOW_CUSTOM_PASSWORD) %>">
Indentation is not aligned, i suppose we should run `gw formatSource` though. Should we?

2023-05-10 00:49 UTC, hhtank commented on modules/apps/login/login-web/src/main/resources/META-INF/resources/create_account.jsp
>  			<div class="form-group">
May hide the form-group and also formatSource

2023-05-10 04:26 UTC, thabet91 commented
@hhtank  please check the changes

2023-05-11 01:00 UTC, hhtank commented
@thabet91 Can you help check check again, i still do see indentation not good so far

![image](https://github.com/hhtank/liferay-portal/assets/15938125/48f2f4dc-c0c2-45e4-b55d-5edb70564fa1)

2023-05-11 04:13 UTC, thabet91 commented
@hhtank I did run formatSource and I retried. It looks formated on my local IDE ( check attached picture). I ran it again and there was no change to the file. This could be an issue about how git render the code view.
![for](https://github.com/hhtank/liferay-portal/assets/86395430/7c8b4f35-828f-408a-83fb-2139f74530ce)

2023-05-11 05:39 UTC, hhtank commented
@thabet91 The changes look good so far. I'm fine with this PR. I'll close this and tell you how to send PR to AppSec team.

2023-05-11 05:39 UTC, closed without merging